test_name: Create a weather entry

stages:
  - name: Check that HTTP status code is 200
    request:
      url: http://localhost:8080/weather
      json:
        city: "berlin"
        date: "11/06/2023"
        temperature: 26
      method: POST
      headers:
        Authorization: "Basic dXNlcjpwYXNzd29yZA=="
        content-type: 'application/json'
    response:
      status_code: 200
      headers:
        Content-Type: 'application/json'
      json:
        city: "berlin"
        date: "11/06/2023"
        temperature: 26